README.md
Add detail to avoid Nabu Casa questions
None
=> 📚Add note to not attempt to use Nabu Casa

README.md
Add troubleshooting note to avoid Pi-hole questions like in #13
=> :books: Add troubleshooting note about Pi-hole issue

README.md
Note rewritten to make the location of the setting clearer. Someone reading the previous version could think it referred to the add-on settings, and not Pi-hole's.
=> :books: Update troubleshooting note to avoid confusion

wireguard/Dockerfile
Upgrade WireGuard and packages to the most recent versions.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> Upgrade WireGuard and packages

LICENSE.md, README.md, wireguard/.README.j2, wireguard/DOCS.md
=> Happy New Year

wireguard/Dockerfile
Upgrade WireGuard Go to the latest available tag.
=> :arrow_up: Upgrades WireGuard Go to 0.0.20201118

.github/workflows/ci.yaml, wireguard/config.json
Ensures the add-on configuration is compatible with Supervisor 2021.2 and newer.
=> Update add-on configuration for Supervisor 2021.2

wireguard/Dockerfile
=> :arrow_up: Upgrades git to 2.30.1-r0

wireguard/Dockerfile
=> ⬆️ Upgrades git to 2.30.2-r0

wireguard/Dockerfile
=> ⬆️ Upgrades go to 1.15.10-r0

wireguard/Dockerfile, wireguard/build.json
Upgrades add-on base image to v9.1.5
=> ⬆️ Upgrades add-on base image to v9.1.5

wireguard/Dockerfile, wireguard/build.json
Upgrades add-on base image to v9.1.7
=> ⬆️ Upgrades add-on base image to v9.1.7

wireguard/Dockerfile
Upgrades WireGuard Go to 0.0.20210212
=> ⬆️ Upgrades WireGuard Go to 0.0.20210212

wireguard/DOCS.md
=> 📚 Minor documentation tweak

wireguard/Dockerfile, wireguard/build.json
Upgrades add-on base image to v9.2.0
=> ⬆️ Upgrades add-on base image to v9.2.0

wireguard/Dockerfile
=> ⬆️ Upgrades go to 1.15.12-r0

wireguard/Dockerfile, wireguard/build.json
Upgrades add-on base image to v10.0.1
=> ⬆️ Upgrades add-on base image to v10.0.1

wireguard/DOCS.md
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> Fixed typo

wireguard/Dockerfile
=> ⬆️ Upgrades go to 1.16.10-r0

wireguard/Dockerfile, wireguard/build.yaml
Upgrades add-on base image to 10.2.2
=> ⬆️ Upgrades add-on base image to 10.2.2

wireguard/Dockerfile
Upgrades WireGuard Go to 0.0.20210424
=> ⬆️ Upgrades WireGuard Go to 0.0.20210424

wireguard/Dockerfile, wireguard/build.yaml
Upgrades add-on base image to 11.0.0
=> ⬆️ Upgrades add-on base image to 11.0.0

wireguard/DOCS.md
Change old reference to hass.io
=> 📚 Change Hass.io reference

wireguard/Dockerfile, wireguard/build.yaml, wireguard/rootfs/etc/cont-init.d/config.sh, wireguard/rootfs/etc/services.d/api/run, wireguard/rootfs/etc/services.d/status/run, wireguard/rootfs/etc/services.d/wireguard/run
Upgrades add-on base image to 12.0.0
closes #193
=> ⬆️ Upgrades add-on base image to 12.0.0

wireguard/Dockerfile
> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/
=> ⬆️ Upgrades WireGuard Go to 0.0.20220316

wireguard/rootfs/etc/services.d/wireguard/run
To make this script compatible with s6-overlay v3
=> 🚑 Fix service path in wireguard service file

LICENSE.md, README.md, wireguard/.README.j2, wireguard/DOCS.md
=> :fireworks: Updates maintenance/license year to 2022

wireguard/DOCS.md
Small tweaks and the addition of the My button to the installation instructions.
=> :books: Small documentation tweaks and updates

.github/workflows/deploy.yaml, wireguard/build.yaml, wireguard/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
=> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

wireguard/Dockerfile, wireguard/build.yaml
Upgrades add-on base image to 12.2.3
=> ⬆️ Upgrades add-on base image to 12.2.3

wireguard/Dockerfile, wireguard/build.yaml
⬆️ Upgrades add-on base image to 12.2.7
=> ⬆️ Upgrades add-on base image to 12.2.7

wireguard/Dockerfile
=> ⬆️ Upgrades WireGuard Go to 0.0.20230223

LICENSE.md, README.md, wireguard/.README.j2, wireguard/DOCS.md
=> :fireworks: Updates maintenance/license year to 2023

README.md, wireguard/build.yaml, wireguard/config.yaml
=> Drop support for armhf & i386

LICENSE.md, README.md, wireguard/.README.j2, wireguard/DOCS.md
=> :fireworks: Updates maintenance/license year to 2024
